title: "Milena Belosevic"
description: " "
 
plugins: [jekyll-remote-theme]
remote_theme: jekyll/minima

header_pages:   
    - research.md
    - publications.md
    - teaching.md
  social_links:
      - { platform: email, user_url: "mailto:milena.belosevic@uni-bielefeld.de" }

